-   id: prevent-commit-submodule
    name: Prevent commits in submodules
    description: This hook prevents developers from committing in submodules.
    entry: prevent-commit-submodule
    language: python
    types: [text]
    stages: [commit, push, manual]
